server:
    port: 8080

spring:
    application:
        name: api-gateway
    cloud:
        gateway:
            routes:
                - id: user-service
                  uri: http://user-service:8081
                  predicates:
                    - Path=/api/users/**
                - id: product-service
                  uri: http://product-service:8082
                  predicates:
                     Path=/api/products/**
                - id: order-service
                  uri: http://order-service:8083
                  predicates:
                      Path=/api/orders/**
                - id: depot-service
                  uri: http://depot-service:8084
                  predicates:
                      Path=/api/depot/**
                - id: supply-service
                  uri: http://supply-service:8084
                  predicates:
                      Path=/api/supply/**

