version: '3.8'
services:
  user-service:
    build: ./user-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
  product-service:
    build: ./product-service
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
  order-service:
    build: ./order-service
    ports:
      - "8083:8083"
  payment-service:
    build: ./payment-service
    ports:
      - "8084:8084"
  gateway-service:
    build: ./gateway-service
    ports:
      - "8080:8080"
